import { Category, Situation } from '@prisma/client';
import { prismaSeed } from '../prisma-seeds';

export async function warningSeed() {
  const warningsData = [
    {
      title: 'Vazamento no Apartamento 102',
      description: 'Vazamento no teto do banheiro.',
      situation: Situation.ABERTO,
      category: Category.MEDIA,
      userId: 3,
      condominiumId: 1,
    },
    {
      title: 'Barulho Excessivo no Apartamento 203',
      description: 'Reclamação de barulho após as 22h.',
      situation: Situation.ANALISE,
      category: Category.ALTA,
      userId: 8,
      condominiumId: 1,
    },
    {
      title: 'Problema com Elevador',
      description: 'Elevador do bloco A com falhas.',
      situation: Situation.ATENDIDO,
      category: Category.GRAVE,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Vazamento na Piscina',
      description: 'Vazamento na área da piscina infantil.',
      situation: Situation.REABERTO,
      category: Category.CRITICA,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Problema na Iluminação da Garagem',
      description: 'Iluminação da garagem com falhas.',
      situation: Situation.SUSPENSO,
      category: Category.MEDIA,
      userId: 14,
      condominiumId: 2,
    },
    {
      title: 'Problema com o Portão da Garagem',
      description: 'Portão da garagem com mau funcionamento.',
      situation: Situation.ABERTO,
      category: Category.ALTA,
      userId: 26,
      condominiumId: 3,
    },
    {
      title: 'Vazamento no Apartamento 301',
      description: 'Vazamento na cozinha.',
      situation: Situation.ANALISE,
      category: Category.MEDIA,
      userId: 7,
      condominiumId: 1,
    },
    {
      title: 'Barulho Excessivo no Apartamento 104',
      description: 'Reclamação de barulho durante o dia.',
      situation: Situation.ATENDIDO,
      category: Category.ALTA,
      userId: 4,
      condominiumId: 1,
    },
    {
      title: 'Problema com Elevador',
      description: 'Elevador do bloco C com falhas.',
      situation: Situation.REABERTO,
      category: Category.GRAVE,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Vazamento no Salão de Festas',
      description: 'Vazamento no teto do salão de festas.',
      situation: Situation.SUSPENSO,
      category: Category.CRITICA,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Problema na Iluminação da Quadra',
      description: 'Iluminação da quadra com falhas.',
      situation: Situation.ABERTO,
      category: Category.MEDIA,
      userId: 15,
      condominiumId: 2,
    },
    {
      title: 'Problema com o Portão Social',
      description: 'Portão social com mau funcionamento.',
      situation: Situation.ANALISE,
      category: Category.ALTA,
      userId: 27,
      condominiumId: 3,
    },
    {
      title: 'Vazamento no Apartamento 202',
      description: 'Vazamento no quarto.',
      situation: Situation.ATENDIDO,
      category: Category.MEDIA,
      userId: 5,
      condominiumId: 1,
    },
    {
      title: 'Barulho Excessivo no Apartamento 304',
      description: 'Reclamação de barulho durante a noite.',
      situation: Situation.REABERTO,
      category: Category.ALTA,
      userId: 12,
      condominiumId: 1,
    },
    {
      title: 'Problema com Elevador',
      description: 'Elevador do bloco B com falhas.',
      situation: Situation.SUSPENSO,
      category: Category.GRAVE,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Vazamento na Churrasqueira',
      description: 'Vazamento na área da churrasqueira.',
      situation: Situation.ABERTO,
      category: Category.CRITICA,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Problema na Iluminação da Piscina',
      description: 'Iluminação da piscina com falhas.',
      situation: Situation.ANALISE,
      category: Category.MEDIA,
      userId: 16,
      condominiumId: 2,
    },
    {
      title: 'Problema com o Portão da Piscina',
      description: 'Portão da piscina com mau funcionamento.',
      situation: Situation.ATENDIDO,
      category: Category.ALTA,
      userId: 28,
      condominiumId: 3,
    },
    {
      title: 'Vazamento no Apartamento 103',
      description: 'Vazamento na sala.',
      situation: Situation.REABERTO,
      category: Category.MEDIA,
      userId: 6,
      condominiumId: 1,
    },
    {
      title: 'Barulho Excessivo no Apartamento 201',
      description: 'Reclamação de barulho durante o dia.',
      situation: Situation.SUSPENSO,
      category: Category.ALTA,
      userId: 2,
      condominiumId: 1,
    },
    {
      title: 'Problema com Elevador',
      description: 'Elevador do bloco A com falhas.',
      situation: Situation.ABERTO,
      category: Category.GRAVE,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Vazamento no Espaço Gourmet',
      description: 'Vazamento na área do espaço gourmet.',
      situation: Situation.ANALISE,
      category: Category.CRITICA,
      userId: 1,
      condominiumId: 2,
    },
    {
      title: 'Problema na Iluminação do Espaço Pet',
      description: 'Iluminação do espaço pet com falhas.',
      situation: Situation.ATENDIDO,
      category: Category.MEDIA,
      userId: 17,
      condominiumId: 3,
    },
    {
      title: 'Problema com o Portão do Espaço Pet',
      description: 'Portão do espaço pet com mau funcionamento.',
      situation: Situation.REABERTO,
      category: Category.ALTA,
      userId: 29,
      condominiumId: 3,
    },
    {
      title: 'Vazamento no Apartamento 302',
      description: 'Vazamento na varanda.',
      situation: Situation.SUSPENSO,
      category: Category.MEDIA,
      userId: 10,
      condominiumId: 1,
    },
    {
      title: 'Barulho Excessivo no Apartamento 101',
      description: 'Reclamação de barulho durante a noite.',
      situation: Situation.ABERTO,
      category: Category.ALTA,
      userId: 2,
      condominiumId: 1,
    },
    {
      title: 'Problema com Elevador',
      description: 'Elevador do bloco C com falhas.',
      situation: Situation.ANALISE,
      category: Category.GRAVE,
      userId: 1,
      condominiumId: 1,
    },
    {
      title: 'Vazamento na Sala de Jogos',
      description: 'Vazamento na área da sala de jogos.',
      situation: Situation.ATENDIDO,
      category: Category.CRITICA,
      userId: 1,
      condominiumId: 2,
    },
    {
      title: 'Problema na Iluminação da Academia',
      description: 'Iluminação da academia com falhas.',
      situation: Situation.REABERTO,
      category: Category.MEDIA,
      userId: 18,
      condominiumId: 3,
    },
    {
      title: 'Problema com o Portão da Academia',
      description: 'Portão da academia com mau funcionamento.',
      situation: Situation.SUSPENSO,
      category: Category.ALTA,
      userId: 30,
      condominiumId: 3,
    },
  ];

  try {
    await prismaSeed.warning.upsert({
      where: { id: 1 },
      update: {},
      create: data,
    });
    console.log('Aviso criado ou atualizado com sucesso!');
  } catch (error) {
    console.error('Erro ao criar ou atualizar o aviso', error);
  }
}
